spring:
  datasource:
    hikari:
      connection-timeout: 10000
    url: ${datasource}?createDatabaseIfNotExist = true
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
